sql:
  enabled: false
  hostname: host
  port: 3306
  database: database
  username: user
  password: password
settings:
  minimumConnections: 2
  maximumConnections: 5
  timeout: 30000
  poolname: CraftLibs

updater:
  enabled: false
  plugins:
    - 'example'

server-id: ''